#!/usr/bin/env python
#
# Script that converts a yum comps file into output that can be
# inserted into the %packages section of a kickstart script. By
# default it only prints groups (sans language groups) and commented
# optional packages. Options are provided to print the mandatory or
# default packages.
#
# I borrowed from yum-groups-manager to understand how yum.comps worked.
#

import os
import sys
import gzip
import optparse
import yum.comps

def print_err(*args):
    sys.stderr.write(' '.join(map(str,args)) + '\n')
    sys.stderr.flush()

def setup_opts():
    parser = optparse.OptionParser(usage="%prog [OPTS...] FILE", version="0.0.1")
    parser.add_option("-a", "--all", action="store_true", dest="all", help="show all groups")
    parser.add_option("-e", "--exclude", action="append", default=[], dest="exclude", help="exclude groups")
    parser.add_option("-d", "--defaults", action="store_true", default=False, dest="defaults", help="show packages installed by default")
    parser.add_option("-l", "--lang", action="append", default=[], dest="lang", help="show language support groups")
    return parser

def main():
    # Parse the application options
    parser = setup_opts()
    (opts, args) = parser.parse_args()
    
    # Make sure we got the file argument
    fname = None
    if len(args) < 1:
        print_err("Error: no file provided")
        sys.exit(1)
    else:
        fname = args[0]
    
    # Create the comps object and read in the file
    comps = yum.comps.Comps()
    try:
        if not os.path.exists(fname):
            print_err("File not found: %s" % fname)
            sys.exit(1)
        if fname.endswith('.gz'):
            fname = gzip.open(fname)
        comps.add(srcfile=fname)
    except IOError, e:
        print_err("Error: couldn't open %s" % fname)
        sys.exit(1)
    
    # Add 'conflicts' and 'everything' to the
    # list of excluded groups
    opts.exclude.append("conflicts")
    opts.exclude.append("everything")
    
    # Get all the groups in the comps file and sort it
    groups = comps.return_groups(group_pattern='*', case_sensitive=False)
    groups = sorted(groups, key=lambda x: x.name)
    
    # Loop through all the groups
    for group in groups:
        # Skip group if it is a language group that
        # is not in the language list or if the -a
        # option was not used
        if group.langonly:
            if not group.langonly in opts.lang:
                if not opts.all:
                    continue
        
        # Skip any groups that have been
        # explicitly excluded
        if group.groupid in opts.exclude:
            continue
        
        # Print the group id
        print "@" + str(group.groupid)
        
        # Print mandatory and default packages if the
        # option was specified
        if opts.defaults:
            for mp in group.mandatory_packages:
                print str(mp)
            for dp in group.default_packages:
                print str(dp)
        
        # Print the optional packages
        for op in group.optional_packages:
            print "#" + str(op)

# Run the main function if being run as a script
if __name__ == "__main__":
    main()
